runtime: python312


env_variables:
  DB_USER: "tastehub-db"
  DB_NAME: "tastehub_db"
  DB_CONNECTION_NAME:"restaurantapp-480515:europe-west2:tastehub-db"

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

